Updates

diff --git a/shell-scripts/screenrec b/shell-scripts/screenrec
--- a/shell-scripts/screenrec
+++ b/shell-scripts/screenrec
@@ -16,8 +16,8 @@ case $1 in
       *) echo " USAGE: screenrec <output_filename.mp4>" ; exit 1 ;;
 esac
 
-which xwininfo || { echo 'xwininfo not found. Exiting.' ; exit 1; }
-which ffmpeg || { echo 'ffmpeg not found. Exiting.' ; exit 1; }
+which xwininfo > /dev/null 2>&1 || { echo 'xwininfo not found. Exiting.' ; exit 1; }
+which ffmpeg > /dev/null 2>&1 || { echo 'ffmpeg not found. Exiting.' ; exit 1; }
 
 printf "\n Click on the target window to begin screen recording.\n
  Press 'q' to stop recording after selecting the target window.\n"
@@ -32,6 +32,10 @@ if [[ "$height $width $xpos $ypos" == *-* ]]; then
   printf "\n ERROR: Invalid screen position detected! Is the target window hanging off of the screen?\n\n"
   exit 1
 fi
+
+# bug fix since ffmpeg cannot handle window resolutions that are (even)x(even)
+if [ $((height%2)) -ne 0 ]; then height=$((height+1)) ; fi
+if [ $((width%2)) -ne 0 ]; then width=$((width+1)) ; fi
 
 ffmpeg -f x11grab -video_size ${width}x${height} -framerate 18 -i :0.0+${xpos},${ypos} -vf format=yuv420p $1
 
