Updates

diff --git a/shell-scripts/screenrec b/shell-scripts/screenrec
--- a/shell-scripts/screenrec
+++ b/shell-scripts/screenrec
@@ -1,35 +1,98 @@
-#! /bin/bash
+# /bin/bash
 
 #=======================================================================
 #
-# screenrec <output_filename.mp4>
+# screenrec [-o output_file] -w|-s
 #
-# This is a simple script that uses ffmpeg to record the screen of a
-# selected window.
+# This is a simple script that uses ffmpeg to record the screen.
 #
-# NOTE: This script assumes you have xwininfo and ffmpeg installed
+# NOTE: This script assumes you have xwininfo, ffmpeg and slop installed
 #
 #=======================================================================
 
-case $1 in
-      *.mp4) ;;
-      *) echo " USAGE: screenrec <output_filename.mp4>" ; exit 1 ;;
-esac
+# usage instructions
+usage() {
+    echo "Usage: $0 [-o output_file] -w|-s"
+    echo "Options:"
+    echo "  -o <output_file>: Output MP4 file"
+    echo "  -w: Record an entire application window"
+    echo "  -s: Record a user-specified selection of the screen"
+    echo 
+    echo " Please provide one of -w or -s (but not both)."
+    exit 1
+}
 
+# checking for installed software
 which xwininfo > /dev/null 2>&1 || { echo 'xwininfo not found. Exiting.' ; exit 1; }
 which ffmpeg > /dev/null 2>&1 || { echo 'ffmpeg not found. Exiting.' ; exit 1; }
+which slop > /dev/null 2>&1 || { echo 'ffmpeg not found. Exiting.' ; exit 1; }
 
-printf "\n Click on the target window to begin screen recording.\n
- Press 'q' to stop recording after selecting the target window.\n"
-xwininfo > /tmp/windata.tmp
+# parse command-line arguments
+while getopts "o:ws" opt; do
+    case $opt in
 
-height=`cat /tmp/windata.tmp | grep Height | cut -d' ' -f4`
-width=`cat /tmp/windata.tmp | grep Width | cut -d' ' -f4`
-xpos=`cat /tmp/windata.tmp | grep "Absolute upper-left X" | cut -d' ' -f7`
-ypos=`cat /tmp/windata.tmp | grep "Absolute upper-left Y" | cut -d' ' -f7`
+        o) # append .mp4 extension if not provided
+           output_file=$OPTARG
+           if [[ ! $output_file == *".mp4" ]]; then output_file="$output_file.mp4"; fi
+           ;;
 
+        w) wflag=1 ;;
+        
+        s) sflag=1 ;;
+
+        *) usage ;;
+
+    esac
+done
+
+# check for either -w or -s (but not both)
+if [[ -n "$wflag" || -n "$sflag" ]]; then
+  if [[ -n "$wflag" && -n "$sflag" ]]; then usage; fi
+else
+  usage
+  exit 1
+fi
+
+# check for output filename
+if [[ -z $output_file ]]; then
+  echo
+  current_time=$(date +"%Y-%m-%d_%H-%M-%S")
+  output_file="output_${current_time}.mp4"
+  echo " No output filename provided... Saving to default file: ${output_file}"; echo
+fi
+
+# get relevant screen data
+if [[ -n "$wflag" ]]; then
+
+  echo
+  echo " Click on the target window to begin screen recording."
+  echo " Press 'q' to stop recording after selecting the target window."; echo
+  xwininfo > /tmp/windata.tmp
+
+  width=`cat /tmp/windata.tmp | grep Width | cut -d' ' -f4`
+  height=`cat /tmp/windata.tmp | grep Height | cut -d' ' -f4`
+  xpos=`cat /tmp/windata.tmp | grep "Absolute upper-left X" | cut -d' ' -f7`
+  ypos=`cat /tmp/windata.tmp | grep "Absolute upper-left Y" | cut -d' ' -f7`
+
+elif [[ -n "sflag" ]]; then
+
+  echo
+  echo " Select a target area with your cursor to begin screen recording."
+  echo " Press 'q' to stop recording after selecting the target area."; echo
+  slop > /tmp/windata.tmp 2> /dev/null
+
+  width=$(cat /tmp/windata.tmp | cut -d 'x' -f 1)
+  height=$(cat /tmp/windata.tmp | cut -d 'x' -f 2 | cut -d '+' -f 1)
+  xpos=$(cat /tmp/windata.tmp | cut -d '+' -f 2)
+  ypos=$(cat /tmp/windata.tmp | cut -d '+' -f 3)
+
+fi
+
+# check for valid screen selection
 if [[ "$height $width $xpos $ypos" == *-* ]]; then
-  printf "\n ERROR: Invalid screen position detected! Is the target window hanging off of the screen?\n\n"
+  echo
+  echo "ERROR: Invalid screen selection detected! Is the target area hanging off of the screen?"
+  echo
   exit 1
 fi
 
@@ -37,7 +100,11 @@ fi
 if [ $((height%2)) -ne 0 ]; then height=$((height+1)) ; fi
 if [ $((width%2)) -ne 0 ]; then width=$((width+1)) ; fi
 
-ffmpeg -f x11grab -video_size ${width}x${height} -framerate 18 -i :0.0+${xpos},${ypos} -vf format=yuv420p $1
+# record the intended area
+ffmpeg -f x11grab -video_size ${width}x${height} -framerate 18 -i :0.0+${xpos},${ypos} -vf format=yuv420p ${output_file} || exit 1
 
-printf "\n File written to $1\n"
-du -hs ./$1
+echo
+echo " File written to $output_file"
+echo 
+
+du -h ./$output_file
